### ISSUE TITLE
Build failure on AArch64

### ISSUE THREAD

**Issue by MingcongBai** [MoonchildProductions/Pale-Moon#1626]
Seems like something's missing...

```
131:51.86 jidctint.o
131:53.94 jidctred.o
131:54.22 jmemmgr.o
131:54.78 jmemnobs.o
131:54.90 jquant1.o
131:55.42 jquant2.o
131:56.35 jutils.o
131:56.48 jsimd_arm64.o
131:56.75 jsimd_arm64_neon.o
131:56.75 make[5]: o: Command not found
131:56.76 libmedia_libjpeg.a.desc
131:56.82 Traceback (most recent call last):
131:56.82   File "/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/config/expandlibs_gen.py", line 41, in <module>
131:56.82     print >>outfile, generate(args)
131:56.82   File "/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/config/expandlibs_gen.py", line 22, in generate
131:56.82     raise Exception("File not found: %s" % arg)
131:56.82 Exception: File not found: jsimd_arm64_neon.o
131:56.83 make[5]: *** [/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/config/rules.mk:782: libmedia_libjpeg.a.desc] Error 1
131:56.83 make[5]: *** Deleting file 'libmedia_libjpeg.a.desc'
131:56.83 make[4]: *** [/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/config/recurse.mk:74: media/libjpeg/target] Error 2
131:56.83 make[3]: *** [/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/config/recurse.mk:37: compile] Error 2
131:56.83 make[2]: *** [/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/config/rules.mk:541: default] Error 2
131:56.83 make[1]: *** [/var/cache/acbs/build/acbs.4xlkk5cu/palemoon/client.mk:399: realbuild] Error 2
131:56.83 make: *** [client.mk:171: build] Error 2
131:56.85 192 compiler warnings present.
131:57.03 Notification center failed: Unable to autolaunch a dbus-daemon without a $DISPLAY for X11
```

**Comment by MingcongBai** [comment]
Build information:

- Glibc: 2.26
- GCC: 5.4
- Pale Moon source: 27.7.2

**Comment by wolfbeast** [comment]
"FTBFS"?

**Comment by MingcongBai** [comment]
Fails To Build From Source. Sorry...

**Comment by janekptacijarabaci** [comment]
AFAIK: A possibly-related bug: `libjpeg-turbo assembly doesn't build on mips and arm64` - [bug 1165654](https://bugzilla.mozilla.org/show_bug.cgi?id=1165654)

**Comment by wolfbeast** [comment]
Try applying this patch: https://hg.mozilla.org/mozilla-central/rev/45ecf64767d6

**Comment by MingcongBai** [comment]
The patch unfortunately does not apply...

**Comment by MingcongBai** [comment]
Any ideas?

**Comment by adeshkp** [comment]
Since the patch is quite old, and also due to divergence of codebases, the patch may not apply cleanly. In this case, you'll have to make the changes manually.

**Comment by wolfbeast** [comment]
Only if it's an officially supported architecture -- which it isn't. Not at this time anyway.
