### ISSUE TITLE
Mac build : ImportError: dlopen(/Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder

### ISSUE THREAD

**Issue by sebma** [MoonchildProductions/Pale-Moon#1690]
Hi,

I'm following this [guide from developer.palemoon.org](https://developer.palemoon.org/Developer_Guide:Build_Instructions/Pale_Moon/macOS) and I get the following output on Macos X 10.13 High Sierra : 

```python
./mach build
 0:00.52 /usr/local/bin/gmake -f client.mk -s
 0:02.95 Adding client.mk options from :
 0:02.95     MOZ_OBJDIR=/Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0
 0:02.95     OBJDIR=/Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0
 0:03.80 => FOUND_MOZCONFIG = <>
 0:03.80 usage: cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file target_file
 0:03.80        cp [-R [-H | -L | -P]] [-fi | -n] [-apvXc] source_file ... target_directory
 0:03.81 cd /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0
 0:03.82 /Users/mansfeld/src/Pale-Moon/configure
 0:04.65 loading cache ./config.cache
 0:04.88 checking host system type... x86_64-apple-darwin17.7.0
 0:04.95 checking target system type... x86_64-apple-darwin17.7.0
 0:05.01 checking build system type... x86_64-apple-darwin17.7.0
 0:05.02 checking for mawk... no
 0:05.02 checking for gawk... gawk
 0:05.04 checking for python2.7... /usr/local/miniconda2/bin/python2.7
 0:05.04 Creating Python environment
 0:05.23 New python executable in /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/bin/python2.7
 0:05.24 Not overwriting existing python script /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/bin/python (you must use /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/bin/python2.7)
 0:05.32 Installing setuptools, pip...
 0:05.32   Complete output from command /Users/mansfeld/src/...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip:
 0:05.32   Traceback (most recent call last):
 0:05.32   File "<string>", line 1, in <module>
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/__init__.py", line 13, in <module>
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv_support/pip-6.0.6-py2.py3-none-any.whl/pip/utils/__init__.py", line 14, in <module>
 0:05.32   File "/usr/local/miniconda2/lib/python2.7/zipfile.py", line 6, in <module>
 0:05.32     import io
 0:05.32   File "/usr/local/miniconda2/lib/python2.7/io.py", line 51, in <module>
 0:05.32     import _io
 0:05.32 ImportError: dlopen(/Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/lib/python2.7/lib-dynload/_io.so, 2): Symbol not found: __PyCodecInfo_GetIncrementalDecoder
 0:05.32   Referenced from: /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/lib/python2.7/lib-dynload/_io.so
 0:05.32   Expected in: flat namespace
 0:05.32  in /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/_virtualenv/lib/python2.7/lib-dynload/_io.so
 0:05.32 ----------------------------------------
 0:05.32 ...Installing setuptools, pip...done.
 0:05.32 Traceback (most recent call last):
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv.py", line 2352, in <module>
 0:05.32     main()
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv.py", line 825, in main
 0:05.32     symlink=options.symlink)
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv.py", line 993, in create_environment
 0:05.32     install_wheel(to_install, py_executable, search_dirs)
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv.py", line 961, in install_wheel
 0:05.32     'PIP_NO_INDEX': '1'
 0:05.32   File "/Users/mansfeld/src/Pale-Moon/python/virtualenv/virtualenv.py", line 903, in call_subprocess
 0:05.32     % (cmd_desc, proc.returncode))
 0:05.32 OSError: Command /Users/mansfeld/src/...ualenv/bin/python2.7 -c "import sys, pip; sys...d\"] + sys.argv[1:]))" setuptools pip failed with error code 1
 0:05.33 Traceback (most recent call last):
 0:05.33   File "/Users/mansfeld/src/Pale-Moon/python/mozbuild/mozbuild/virtualenv.py", line 475, in <module>
 0:05.33     manager.ensure()
 0:05.33   File "/Users/mansfeld/src/Pale-Moon/python/mozbuild/mozbuild/virtualenv.py", line 128, in ensure
 0:05.33     return self.build()
 0:05.33   File "/Users/mansfeld/src/Pale-Moon/python/mozbuild/mozbuild/virtualenv.py", line 371, in build
 0:05.33     self.create()
 0:05.33   File "/Users/mansfeld/src/Pale-Moon/python/mozbuild/mozbuild/virtualenv.py", line 147, in create
 0:05.33     raise Exception('Error creating virtualenv.')
 0:05.33 Exception: Error creating virtualenv.
 0:05.34 ------ config.log ------
 0:05.34 This file contains any messages produced by compilers while
 0:05.34 running configure, to aid debugging if configure makes a mistake.
 0:05.34
 0:05.34 configure:1164: checking host system type
 0:05.35 configure:1185: checking target system type
 0:05.35 configure:1203: checking build system type
 0:05.35 configure:1282: checking for mawk
 0:05.35 configure:1282: checking for gawk
 0:05.35 configure:1367: checking for python2.7
 0:05.35 *** Fix above errors and then restart with\
 0:05.35                "/usr/local/bin/gmake -f client.mk build"
 0:05.35 gmake[2]: *** [/Users/mansfeld/src/Pale-Moon/client.mk:365: configure] Error 1
 0:05.35 gmake[1]: *** [/Users/mansfeld/src/Pale-Moon/client.mk:377: /Users/mansfeld/src/Pale-Moon/obj-x86_64-apple-darwin17.7.0/Makefile] Error 2
 0:05.35 gmake: *** [client.mk:171: build] Error 2
 0:05.39 0 compiler warnings present.
```

Can you please help me ?

**Comment by wolfbeast** [comment]
Please use the forum for this kind of support.
https://forum.palemoon.org/
