### ISSUE TITLE
mediasource: issue decoding twitch.tv

### ISSUE THREAD

**Issue by wolfbeast** [MoonchildProductions/Pale-Moon#702]
@trav90 mainly for you:
Apparently, PM27-release borks on twitch.tv, and beta3 works.

Browser console loops over the following constantly while the error is displayed:
````
Media resource mediasource:https://player.twitch.tv/eedb2a84-5aac-43bb-adf2-501306df1be7 could not be decoded. player.twitch.tv
"Attempted to append to SourceBuffer while MediaSource is closed" player-core-min.js:1:6287

"ElementaryStream_Avc::finishFrame() m_outputDts(706185) != m_fr" player-core-min.js:2:26221
"ElementaryStream_Avc::finishFrame() Frame contains no nalus" player-core-min.js:2:26221
TypeError: this.api is null player-core-min.js:1:5245
no element found spade.twitch.tv:1:1
no element found spade.twitch.tv:1:1
"TransportStream() Found AAC stream at PID 256" player-core-min.js:2:26221
"TransportStream() Found AVC stream at PID 257" player-core-min.js:2:26221
"TransportStream() Found ID3 stream at PID 258" player-core-min.js:2:26221
"CAPTION [clear]" player-core-min.js:2:26221
"fmp4 addTrackAvc() id:1 avc1.4D401E" player-core-min.js:2:26221
"fmp4 addTrackAac() id:2 mp4a.40.2" player-core-min.js:2:26221
"Excessively small DTS delta(0) pid: 257 type:0x1b, min delta: 7" player-core-min.js:2:26221
"Writing Init fragment" player-core-min.js:2:26221
"codec: {"height": 480, "level": "3.0", "mime": "avc1.4D401E", "" player-core-min.js:2:26221
"codec: {"channels": 2, "frequency": 44100, "mime": "mp4a.40.2"}" player-core-min.js:2:26221
Media resource mediasource:https://player.twitch.tv/63120e30-a6cc-48fd-80bc-25314de7e44f could not be decoded. player.twitch.tv
no element found spade.twitch.tv:1:1
"Attempted to append to SourceBuffer while MediaSource is closed" player-core-min.js:1:6287

"ElementaryStream_Avc::finishFrame() m_outputDts(1060515) != m_f" player-core-min.js:2:26221
"ElementaryStream_Avc::finishFrame() Frame contains no nalus" player-core-min.js:2:26221
TypeError: this.api is null player-core-min.js:1:5245
no element found spade.twitch.tv:1:1
"TransportStream() Found AAC stream at PID 256" player-core-min.js:2:26221
"TransportStream() Found AVC stream at PID 257" player-core-min.js:2:26221
"TransportStream() Found ID3 stream at PID 258" player-core-min.js:2:26221
"CAPTION [clear]" player-core-min.js:2:26221
"fmp4 addTrackAvc() id:1 avc1.4D401E" player-core-min.js:2:26221
"fmp4 addTrackAac() id:2 mp4a.40.2" player-core-min.js:2:26221
"Excessively small DTS delta(0) pid: 257 type:0x1b, min delta: 7" player-core-min.js:2:26221
"Writing Init fragment" player-core-min.js:2:26221
"codec: {"height": 480, "level": "3.0", "mime": "avc1.4D401E", "" player-core-min.js:2:26221
"codec: {"channels": 2, "frequency": 44100, "mime": "mp4a.40.2"}" player-core-min.js:2:26221
Media resource mediasource:https://player.twitch.tv/8def28da-3c7d-4434-a677-15decd92c753 could not be decoded. player.twitch.tv
no element found spade.twitch.tv:1:1
"Attempted to append to SourceBuffer while MediaSource is closed" player-core-min.js:1:6287

"ElementaryStream_Avc::finishFrame() m_outputDts(1059579) != m_f" player-core-min.js:2:26221
"ElementaryStream_Avc::finishFrame() Frame contains no nalus" player-core-min.js:2:26221
TypeError: this.api is null player-core-min.js:1:5245
no element found spade.twitch.tv:1:1
"TransportStream() Found AAC stream at PID 256" player-core-min.js:2:26221
"TransportStream() Found AVC stream at PID 257" player-core-min.js:2:26221
"TransportStream() Found ID3 stream at PID 258" player-core-min.js:2:26221
"CAPTION [clear]" player-core-min.js:2:26221
"fmp4 addTrackAvc() id:1 avc1.4D401E" player-core-min.js:2:26221
"fmp4 addTrackAac() id:2 mp4a.40.2" player-core-min.js:2:26221
"Excessively small DTS delta(0) pid: 257 type:0x1b, min delta: 7" player-core-min.js:2:26221
"Writing Init fragment" player-core-min.js:2:26221
"codec: {"height": 480, "level": "3.0", "mime": "avc1.4D401E", "" player-core-min.js:2:26221
"codec: {"channels": 2, "frequency": 44100, "mime": "mp4a.40.2"}" player-core-min.js:2:26221
Media resource mediasource:https://player.twitch.tv/09cf9505-65d1-402a-8e9c-74ba77fd4bfa could not be decoded. player.twitch.tv
no element found spade.twitch.tv:1:1
"Attempted to append to SourceBuffer while MediaSource is closed" player-core-min.js:1:6287

"ElementaryStream_Avc::finishFrame() m_outputDts(1059889) != m_f" player-core-min.js:2:26221
"ElementaryStream_Avc::finishFrame() Frame contains no nalus" player-core-min.js:2:26221
TypeError: this.api is null player-core-min.js:1:5245
no element found
````

**Comment by wolfbeast** [comment]
Backing out merge commit #660 fixes the Twitch playback issue on the relbranch.
Master with its additional commits still doesn't play Twitch, so I think there's something that was overlooked for MediaFormatReader.

**Comment by trav90** [comment]
I'll look into it. Just to confirm - Twitch is broken even with MFR disabled?

**Comment by wolfbeast** [comment]
Yes, it's broken with the commit merged and MFR disabled.

**Comment by wolfbeast** [comment]
I'll let you investigate the master branch to see if you can figure out the issue. I've reverted the relevant breaking code from the relbranch and have been checking several video sites including twitch and it seems to all be OK this way.
=> 27.0.1 seems to be needed; probably want to keep an eye on other bug reports to roll more workarounds or fixes in and aim for next week for that. Sound good for you?

**Comment by trav90** [comment]
Sounds like a plan!
